CREATE TABLE notifications (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL,
    type       TEXT        NOT NULL,
    message    TEXT        NOT NULL,
    ref_type   TEXT,
    ref_id     BIGINT,
    read       BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_notifications_user ON notifications(user_id, read);

CREATE TABLE recurring_rules (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id      BIGINT,
    created_by    BIGINT        NOT NULL,
    description   TEXT          NOT NULL,
    category      TEXT          NOT NULL,
    amount        NUMERIC(19,2) NOT NULL CHECK (amount > 0),
    currency      VARCHAR(3)       NOT NULL,
    cadence       TEXT          NOT NULL,
    interval_days INT,
    next_due_date DATE          NOT NULL,
    active        BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT now()
);
CREATE INDEX idx_recurring_active_due ON recurring_rules(active, next_due_date);

CREATE TABLE recurring_rule_members (
    rule_id BIGINT NOT NULL REFERENCES recurring_rules(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL
);
CREATE INDEX idx_rule_members_rule ON recurring_rule_members(rule_id);

CREATE TABLE payment_obligations (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recurring_rule_id BIGINT        NOT NULL REFERENCES recurring_rules(id) ON DELETE CASCADE,
    due_date          DATE          NOT NULL,
    amount            NUMERIC(19,2) NOT NULL CHECK (amount > 0),
    currency          VARCHAR(3)       NOT NULL,
    description       TEXT          NOT NULL,
    status            TEXT          NOT NULL,
    created_at        TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT uq_obligation_rule_due UNIQUE (recurring_rule_id, due_date)
);
CREATE INDEX idx_obligations_status_due ON payment_obligations(status, due_date);
