CREATE TABLE ledger_entries (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id    BIGINT,                          -- null = personal (non-group) debt
    debtor_id   BIGINT        NOT NULL,
    creditor_id BIGINT        NOT NULL,
    amount      NUMERIC(19,2) NOT NULL CHECK (amount > 0),
    currency    VARCHAR(3)       NOT NULL,
    type        TEXT          NOT NULL,
    ref_type    TEXT          NOT NULL,
    ref_id      BIGINT,
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    -- idempotent event processing: one entry per (cause, debtor, creditor).
    CONSTRAINT uq_ledger_ref UNIQUE (ref_type, ref_id, debtor_id, creditor_id)
);
CREATE INDEX idx_ledger_group_id ON ledger_entries(group_id);
CREATE INDEX idx_ledger_debtor   ON ledger_entries(debtor_id);
CREATE INDEX idx_ledger_creditor ON ledger_entries(creditor_id);

CREATE TABLE settlements (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id                 BIGINT,
    from_user_id             BIGINT        NOT NULL,       -- payer
    to_user_id               BIGINT        NOT NULL,       -- receiver
    amount                   NUMERIC(19,2) NOT NULL CHECK (amount > 0),
    currency                 VARCHAR(3)       NOT NULL,
    status                   TEXT          NOT NULL,
    idempotency_key          TEXT,
    utr                      TEXT,
    claimed_by_user_id       BIGINT,
    claimed_at               TIMESTAMPTZ,
    acknowledged_by_user_id  BIGINT,
    acknowledged_at          TIMESTAMPTZ,
    dispute_reason           TEXT,
    disputed_at              TIMESTAMPTZ,
    version                  BIGINT        NOT NULL DEFAULT 0,
    created_at               TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT uq_settlement_idem UNIQUE (idempotency_key)
);
CREATE INDEX idx_settlements_from ON settlements(from_user_id);
CREATE INDEX idx_settlements_to   ON settlements(to_user_id);
CREATE INDEX idx_settlements_group ON settlements(group_id);
