CREATE TABLE groups (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT        NOT NULL,
    created_by BIGINT      NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE group_members (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id  BIGINT      NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
    user_id   BIGINT      NOT NULL,
    role      TEXT        NOT NULL,
    joined_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (group_id, user_id)
);
CREATE INDEX idx_group_members_user_id ON group_members(user_id);

CREATE TABLE expenses (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id        BIGINT        NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
    description     TEXT          NOT NULL,
    category        TEXT          NOT NULL,
    amount          NUMERIC(19,2) NOT NULL,
    currency        VARCHAR(3)       NOT NULL,
    paid_by_user_id BIGINT        NOT NULL,
    split_type      TEXT          NOT NULL,
    created_by      BIGINT        NOT NULL,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    version         BIGINT        NOT NULL DEFAULT 0
);
CREATE INDEX idx_expenses_group_id ON expenses(group_id);

CREATE TABLE expense_splits (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_id  BIGINT        NOT NULL REFERENCES expenses(id) ON DELETE CASCADE,
    user_id     BIGINT        NOT NULL,
    owed_amount NUMERIC(19,2) NOT NULL
);
CREATE INDEX idx_expense_splits_expense_id ON expense_splits(expense_id);
